### ISSUE TITLE
Error displaying language strings in assign submissions

### ISSUE THREAD

**Issue by Kemmotar83** [compilatio/moodle-plagiarism_compilatio#122]
Hi,

when displaying the result in "submissions page", using the Italian language, the html breaks. The language strings "aiscore" and "ai_score_not_included ", that should be displayed in the popup window, are partially displayed in the main report object (you can see the screenshot below).

![image](https://github.com/compilatio/moodle-plagiarism_compilatio/assets/3964915/60bce481-0c7d-4540-9d9d-e47f9435a862)

I thought immediately of a specific language error but, after some tests, it seems the problems could be related to a wrong (or missing) parsing of special characters. In the Italian version we have quotes which break HTML.

Regards,
Giorgio

**Comment by Kemmotar83** [comment]
Hi,

I don't think this is the solution. You cannot change Italian language, since those quotes are correct.
I think the solution should be the correct handling of special characters.

Thanks,
Giorgio

**Comment by nr-Compilatio** [comment]
Hello,
A fix is on PLUGIN_320_DEV branch. It will be published in plugin 3.2.0.
