### ISSUE TITLE
Issue with Deprecated Callback in Plagiarism Compilatio Plugin on Moodle 4.4

### ISSUE THREAD

**Issue by gjalam** [compilatio/moodle-plagiarism_compilatio#126]
Hello,

I am encountering an issue with the Plagiarism Compilatio plugin on Moodle 4.4. I receive the following error:

Callback before_standard_top_of_body_html in plagiarism_compilatio component should be migrated to new hook callback for core\hook\output\before_standard_top_of_body_html_generation
line 7472 of /lib/moodlelib.php: call to debugging()
line 7539 of /lib/moodlelib.php: call to {closure}()
line 91 of /lib/classes/hook/output/before_standard_top_of_body_html_generation.php: call to get_plugins_with_function()
line 832 of /lib/outputrenderers.php: call to core\hook\output\before_standard_top_of_body_html_generation->process_legacy_callbacks()
line 219 of /lib/mustache/src/Mustache/Context.php: call to core_renderer->standard_top_of_body_html()
line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
line 30 of /data/moodledata/localcache/mustache/1721484800/boost_union/__Mustache_c4e295fe06d3b1cfa93c557453b9e4d0.php: call to Mustache_Context->findDot()
line 66 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_c4e295fe06d3b1cfa93c557453b9e4d0->renderInternal()
line 216 of /lib/outputrenderers.php: call to Mustache_Template->render()
line 219 of /theme/boost_union/layout/drawers.php: call to renderer_base->render_from_template()
line 1483 of /lib/outputrenderers.php: call to include()
line 1408 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 3083 of /lib/outputrenderers.php: call to core_renderer->header()
line 2070 of /lib/setuplib.php: call to core_renderer->fatal_error()
line 470 of /lib/setuplib.php: call to bootstrap_renderer->__call()
line ? of unknownfile: call to default_exception_handler()
It appears that the before_standard_top_of_body_html callback is deprecated and should be replaced with the new hook core\hook\output\before_standard_top_of_body_html_generation.

Could you please provide guidance on how to resolve this issue, or release an update to the plugin that addresses this deprecated callback?

Thank you for your assistance.

Best regards

**Comment by nr-Compilatio** [comment]
Hello,
See issue: https://github.com/compilatio/moodle-plagiarism_compilatio/issues/121
