### ISSUE TITLE
PHP Notice: Undefined index from cron tasks

### ISSUE THREAD

**Issue by ffeytout** [compilatio/moodle-plagiarism_compilatio#31]
Hi, I installed the latest (2.5.1 - 2019030500) version on my upgraded 3.7 and there is something fishy in your cron : 
`PHP Notice: Undefined index: compilatio_password in [...]/plagiarism/compilatio/lib.php on line 2027
PHP Notice: Undefined index: compilatio_api in [...]/plagiarism/compilatio/lib.php on line 2028
PHP Notice: Undefined index: compilatio_password in [...]/plagiarism/compilatio/lib.php on line 1994
PHP Notice: Undefined index: compilatio_api in [...]plagiarism/compilatio/lib.php on line 1995
PHP Notice: Undefined index: compilatio_password in [...]/plagiarism/compilatio/lib.php on line 2046
PHP Notice: Undefined index: compilatio_api in [...]/plagiarism/compilatio/lib.php on line 2047`

This might be related : https://github.com/compilatio/moodle-plagiarism_compilatio/issues/25

**Comment by danmarsden** [comment]
that error looks more to me like you haven't hit the admin upgrade settings.php page - typically when you install a new plugin it will ask you to save values for the settings within the plugin - either that or the plugin isn't saving default values correctly... In any case, to use compilatio you need to set up the api address/account/password in the settings page, it does seem weird to install a plagiarism plugin without enabling it and setting an api address/password etc. If you don't have a valid compilatio account you should probably delete it from your system anyway.

**Comment by ffeytout** [comment]
My university has an account. It went without saying, but you are right I should have mentioned it. 
And this is the only external plugin that does that after my major upgrade from 3.5 to 3.7, so I don't think it's upgrade related.  Between my admin experience and your issue #25 I do think the problem is on the plugin side.
Cheers
