### ISSUE TITLE
compilatio reveal real name during anonymous Assignment (Assignment activity)

### ISSUE THREAD

**Issue by markham89** [compilatio/moodle-plagiarism_compilatio#36]
HI,

I use Assignment activity with anonymous option
when a teacher run compilation plugins real name of attendee are reveal in error message

here : (toto is real name)
(participant)  (is default french anonymous prefix)

<img width="1028" alt="Capture d’écran 2020-04-24 à 13 02 17" src="https://user-images.githubusercontent.com/1396909/80205999-e44a1f00-862b-11ea-82a0-5ad96ddb7782.png">

**Comment by compilatio** [comment]
Hello, this issue has been fixed in Master branch
The anonymized user is now displayed instead of the user's name
![image](https://user-images.githubusercontent.com/5691169/129914681-48a87a9b-f1c8-4b4f-b7fb-8fae7df41082.png)
