### ISSUE TITLE
Upgrade failed : Call to undefined function compilatio_update_meta()

### ISSUE THREAD

**Issue by bcourtin** [compilatio/moodle-plagiarism_compilatio#48]
Hello, 

We have found an upgrade issue in the last publish version

Last version 2021021800 
Moodle version 3.5.16

Upgrade trace : 

!!! Exception : Call to undefined function compilatio_update_meta() !!!
!! 
Error code: generalexceptionmessage !!
!! Stack trace: * line 181 of /plagiarism/compilatio/db/upgrade.php: Error thrown
* line 632 of /lib/upgradelib.php: call to xmldb_plagiarism_compilatio_upgrade()
* line 1857 of /lib/upgradelib.php: call to upgrade_plugins()
* line 182 of /admin/cli/upgrade.php: call to upgrade_noncore()

thanks

**Comment by compilatio** [comment]
Hello,
Master branch have been fixed
