### ISSUE TITLE
costly SQL requests on table "files" with no indexes

### ISSUE THREAD

**Issue by prigaux** [compilatio/moodle-plagiarism_compilatio#50]
moodle-plagiarism_compilatio is doing:
```php
            $mdlsubmissionfiles = $DB->get_records('files',
                array('itemid' => $eventdata["objectid"], 'filearea' => 'submission_files'));
```
(from https://github.com/compilatio/moodle-plagiarism_compilatio/blob/master/lib.php#L2948-L2949 )

There is no index for this kind of requests ([ref](https://github.com/moodle/moodle/blob/master/lib/db/install.xml#L2537)).

Our moodle has 3.5M lines in table `files`, which makes these requests very slow (~7s)
After updating to compilatio plugin version 2.5.8, `POST /mod/assign/view.php` started to take ~7s.
After `create index idx_files_for_compilatio on mdl_files (itemid, filearea);`, those requests take <1s again

**Comment by compilatio** [comment]
This issue has been fixed in the last version of the plugin : 2.5.9 (2021042200).
These requests has been modified to use the indexed fields.
