### ISSUE TITLE
Add plagiarism support to essay questions

### ISSUE THREAD

**Issue by ndunand** [compilatio/moodle-plagiarism_compilatio#57]
Since Moodle 3.11, it is possible for plagiarism detection plugins to analyse the content of essay questions.

See https://tracker.moodle.org/browse/MDL-32226 for a description and pictures of the feature, and a working code example.

See https://github.com/moodle/moodle/blob/master/plagiarism/upgrade.txt for the developer documentation.

**Comment by compilatio** [comment]
Support of essay questions in quiz is now available in the last version of the plugin : 2.6.0 (2021062300).

**Comment by danmarsden** [comment]
great to see compilatio add support for this too - nice work team! :-)

**Comment by ndunand** [comment]
Thanks @compilatio for your quick action on this !

I can confirm I was able to test and have it working as expected ... all is well apart from the small issue I mentioned in #60
