### ISSUE TITLE
localization should use AMOS

### ISSUE THREAD

**Issue by ndunand** [compilatio/moodle-plagiarism_compilatio#59]
Hello,

The official distribution of the plugin should only include `lang/en`. Other localizations should make use of AMOS, for instance for French: https://lang.moodle.org/local/amos/view.php?t=1624611232&v=l&l=fr&c=plagiarism_compilatio&s&d

**Comment by danmarsden** [comment]
Although, sometimes maintainers of a plugin will want to maintain control over certain languages - especially when their main market is non english language speaking. Putting it in AMOS passes control over to the community and the language pack maintainer. Usually this is fine, but it's not a requirement afaik.

**Comment by ndunand** [comment]
I thought this was a requirement ... but that's not really a problem indeed, thanks @danmarsden for jumping in 😊 .

**Comment by danmarsden** [comment]
yeah - it's more a guideline / best practice - but it does hand over control of the lang strings to a community member which is often not what a commercial plugin will want for the "primary language" of most of their users.
