### ISSUE TITLE
calls to new unexisting "nb_mots_min" setting

### ISSUE THREAD

**Issue by ndunand** [compilatio/moodle-plagiarism_compilatio#60]
In several places in `lib.php` there are calls to

    get_config('plagiarism_compilatio', 'nb_mots_min')

This setting does not exist, so this call always returns `false`. Only when the code passes through https://github.com/compilatio/moodle-plagiarism_compilatio/blob/master/lib.php#L1922 is the setting set. That means that I have to try and send an answer with <100 words (it appears) so that the API sends back this information ("the lower limit is 100 words") for this value to be set, and the issue not to appear anymore.

In our case, the result of this is a weird display with a sentence missing a word:

<img width="1050" alt="Screen Shot 2021-06-25 at 11 05 03" src="https://user-images.githubusercontent.com/762972/123399692-34f93700-d5a5-11eb-8916-0794471fab8a.png">

**Comment by compilatio** [comment]
Hello, this issue has been fixed in Master branch
