### ISSUE TITLE
configuration of build 2021112400

### ISSUE THREAD

**Issue by GillesCarpentier** [compilatio/moodle-plagiarism_compilatio#62]
Bonjour,
I just downloaded and installed the last build of the compilatio  plugin on Moodle 3.11.4+. The install process seems to terminates successfully but then, it is not possible to configure it : 

- it does not appear in the Plagiarism category
- nothing happens when you click on compilation in the list of plugins
- no parameter icon is displayed after compilatio 

![CompilatioNoParameter](https://user-images.githubusercontent.com/84851991/143274502-27fd7a78-8e56-41b6-9e8b-68b7cdf4c314.PNG)

Merci d'avance.

**Comment by compilatio** [comment]
Hello,

You have to enable plagiarism plugin in 'Site Administration' > 'Advanced features':
![image](https://user-images.githubusercontent.com/5691169/150377771-2deb344d-855a-4292-b0d7-54fac6e95be1.png)
