### ISSUE TITLE
The setting plagiarism:compilatio_use is deprecated. Use plagiarism_compilatio:enabled instead

### ISSUE THREAD

**Issue by jonathanjoegit** [compilatio/moodle-plagiarism_compilatio#67]
We have this message in our moodle 3.10 :

The setting plagiarism:compilatio_use is deprecated. Use plagiarism_compilatio:enabled instead
line 204 of /lib/plagiarismlib.php: call to debugging()
line 42 of /lib/plagiarismlib.php: call to plagiarism_load_available_plugins()
line 545 of /mod/forum/classes/local/exporters/post.php: call to plagiarism_get_links()
line 411 of /mod/forum/classes/local/exporters/post.php: call to mod_forum\local\exporters\post->get_message()
line 125 of /lib/classes/external/exporter.php: call to mod_forum\local\exporters\post->get_other_values()
line 146 of /mod/forum/classes/local/exporters/posts.php: call to core\external\exporter->export()
line ? of unknownfile: call to mod_forum\local\exporters\posts->mod_forum\local\exporters\{closure}()
line 148 of /mod/forum/classes/local/exporters/posts.php: call to array_map()
line 125 of /lib/classes/external/exporter.php: call to mod_forum\local\exporters\posts->get_other_values()
line 173 of /mod/forum/classes/local/builders/exported_posts.php: call to core\external\exporter->export()
line 95 of /mod/forum/classes/local/renderers/posts.php: call to mod_forum\local\builders\exported_posts->build()
line 212 of /mod/forum/classes/local/renderers/discussion.php: call to mod_forum\local\renderers\posts->render()
line 337 of /mod/forum/discuss.php: call to mod_forum\local\renderers\discussion->render()

**Comment by compilatio** [comment]
Hello, 
The use of this deprecated parameter has been corrected in the version 2.5.4 of the plugin.
If you update your Compilatio plugin, this warning should not be displayed anymore in logs.

**Comment by CartierPierre** [comment]
Hello
We are using the 2.6.2 build 2022051600, looks like this one : https://moodle.org/plugins/plagiarism_compilatio/2.6.2/26700
Why there is an other 2.6.2 more recent ? build 2022071200. Why not upgrading to 2.6.3 ?
I'll update the plugin then.
