### ISSUE TITLE
Migration behind proxy

### ISSUE THREAD

**Issue by Amagansett** [compilatio/moodle-plagiarism_compilatio#71]
Hi !

The migration script "Migration v4 to v5" doesn't run behind a proxy (https://github.com/compilatio/moodle-plagiarism_compilatio/blob/master/ajax/migration.php#L38)

Maybe the script should get proxy values from the moodle config file /config.php ?
as in https://github.com/compilatio/moodle-plagiarism_compilatio/blob/b8b2505aee8b49d9655aa433c56effec8a4676d2/lib.php#L3448

function compilatio_get_compilatio_service($apiconfigid) {

    global $CFG;

    return compilatioservice::getinstance($apiconfigid,
        $CFG->proxyhost,
        $CFG->proxyport,
        $CFG->proxyuser,
        $CFG->proxypassword);
}
Regards,
Cyril

**Comment by compilatio** [comment]
Hello Cyril,

Thanks for reporting this issue, Master branch has been fixed to use Moodle proxy settings on new Curl requests (used for migration).

Regards.
