### ISSUE TITLE
Notice compilatio 2.6.7 2022092800

### ISSUE THREAD

**Issue by jonathanjoegit** [compilatio/moodle-plagiarism_compilatio#74]
When we want to add an H5P content in moodle 3.10, this notice appears (debug = on)

The setting plagiarism:compilatio_use is deprecated. Use plagiarism_compilatio:enabled instead
line 204 of /lib/plagiarismlib.php: call to debugging()
line 90 of /lib/plagiarismlib.php: call to plagiarism_load_available_plugins()
line 383 of /course/modlib.php: call to plagiarism_save_form_elements()
line 180 of /course/modlib.php: call to edit_module_post_actions()
line 168 of /course/modedit.php: call to add_moduleinfo()

Can you correct this please ?

Jonathan
Le Mans Université
<img width="650" alt="Screenshot 2022-10-10 at 16 05 34" src="https://user-images.githubusercontent.com/12695763/194884818-58fa0f53-8991-4ee4-9bed-441936c4874a.png">
<img width="1105" alt="Screenshot 2022-10-10 at 16 05 53" src="https://user-images.githubusercontent.com/12695763/194884851-19a2992e-62ff-4a5a-995d-3dccb5102c10.png">

**Comment by Kemmotar83** [comment]
Hi, is it possible to fix this? Even if you said to have fixed this issue (#67), the latest version 2.6.13 with Moodle 3.11 still have this annoying warning.

Thanks.

**Comment by ndunand** [comment]
+1 same here, would be great to have a fix for this

**Comment by benoitcompilatio** [comment]
Hello,

This has been fixed in version 2.7.1
