### ISSUE TITLE
Compilatio container breaks the new boost drawer layout

### ISSUE THREAD

**Issue by Benjamin-unige** [compilatio/moodle-plagiarism_compilatio#83]
The `#compilatio-container` and `#compilatio-button-container` elements (ie. the one displayed on assignment grading page) are printed outside of the `#page` element.
Doing so prevents it from being properly resized when the side drawers are opened, the drawers go on top of it, obstructing the compilatio block.
It also has the side effect of preventing the compilatio block to correctly scroll with the rest of the page.

The compilatio container should probably be called in the `#page` element or the `#topofscroll .main-inner` element

**Comment by zabellemotte** [comment]
Here is the small css patch that add margins to the compilatio block to stop the block overlap:
#compilatio-container{
margin: 70px 330px 20px 300px;
}
This is not a perfect solution but it looks better.

**Comment by benoitcompilatio** [comment]
Hello,

Since version 2023071800 (2.7.0) of the plugin, the Compilatio container can be minimized to prevent it from taking up a large part of the screen
The container will also be improved in a future version to take up less space
Having no better solution for the moment, I close this issue
Feel free to reopen it if you have any suggestions

**Comment by zabellemotte** [comment]
We still encounter the problem with compilatio 2023071800 version.

**Comment by zabellemotte** [comment]
Here is the problem with Moodle 4.1.5+ with 2023071800 compilatio plugin.
![Capture d’écran 2023-08-30 à 17 31 33](https://github.com/compilatio/moodle-plagiarism_compilatio/assets/38882780/1c55f9a2-26d3-4239-9670-15ef3238beff)

**Comment by zabellemotte** [comment]
And here is the presentation with the css patch when blocks are unfolded ...
![Capture d’écran 2023-08-30 à 17 33 40](https://github.com/compilatio/moodle-plagiarism_compilatio/assets/38882780/7ec2f4ac-d332-409e-88ae-5e206a21dfca)

**Comment by koenr** [comment]
Yes, same problem here: the compilatio bar crawls under the drawers - probably because it's too wide.
The whole Compilatio appearance is perceived as too intrusive on the screen by our teachers - I disabled the service in Forum for that reason.
I think the top bar is unnecessary.

**Comment by benoitcompilatio** [comment]
Hello,

I've made a few changes to minimize the display of the Compilatio container (especially for the default display)
This is available on [branch 2.7.1](https://github.com/compilatio/moodle-plagiarism_compilatio/tree/PLUGIN_271) if you wanna test it

![compilatio-container](https://github.com/compilatio/moodle-plagiarism_compilatio/assets/142570841/22dfb754-c20a-43d7-8e18-aef1bbe7e562)
