### ISSUE TITLE
Typo in English language string

### ISSUE THREAD

**Issue by koenr** [compilatio/moodle-plagiarism_compilatio#88]
| compilatio_author | plagiarism_compilatio 

Le document ... should be The document (Some French left behind)

**Comment by koenr** [comment]
compilatio_studentemail_help | plagiarism_compilatio 

This will send an e-mail ... should be This will send an email  (no dash in email in English)

**Comment by koenr** [comment]
Empty English language string - please delete
errormigration | plagiarism_compilatio

**Comment by koenr** [comment]
Address is written with double d in English
The combination API key - adress entered is invalid -> The combination API key - address entered is invalid

saved_config_failed | plagiarism_compilatio

**Comment by koenr** [comment]
analyze -> analyse

similarities_disclaimer | plagiarism_compilatio

**Comment by koenr** [comment]
Analyze all documents -> Analyse all documents

startallcompilatioanalysis | plagiarism_compilatio

**Comment by koenr** [comment]
Analyse and contain

This document contain too many words to be analyzed. Maximum size : {$a} words -> This document contains too many words to be analysed. Maximum size : {$a} words

toolong | plagiarism_compilatio

**Comment by koenr** [comment]
The following file(s) can't be analyzed  -> The following file(s) can't be analysed 

 toolong_files | plagiarism_compilatio

**Comment by koenr** [comment]
The following file(s) can't be analyzed  -> The following file(s) can't be analysed 

unextractable_files | plagiarism_compilatio

**Comment by benoitcompilatio** [comment]
Hello,

Thank you for the corrections
Fixed on the 2.7.1 branch ([commit](https://github.com/compilatio/moodle-plagiarism_compilatio/commit/6c0c5c99e573be563c3652c6a11781ea740cde9a)).
