### ISSUE TITLE
Cron frequency advise in language pack wrong

### ISSUE THREAD

**Issue by koenr** [compilatio/moodle-plagiarism_compilatio#89]
On Moodledocs the recommended cron execution is every minute: https://docs.moodle.org/en/Cron. This is teh case since Moodle 3.1 (see https://docs.moodle.org/31/en/Installation_quick_guide#Set_up_cron)

There are very good reasons to do that on heavy loaded Moodle sites. Running it every 15 minutes will make other Moodle functions not work properly.

In the language pack of Compilatio, the recommended cron delay is 15 minutes. (see cron_recommandation | plagiarism_compilatio)

I don't think it's up to a plugin to recommend a different optimal cron time then the main documentation. It's up to the plugin to stay out of trouble if it's background tasks are triggered more then once before finishing.

Please remove the string.

**Comment by benoitcompilatio** [comment]
Hello,

The recommendation is for Compilatio's cron tasks and not for Moodle's global cron.
I've added a clarification to avoid confusion: "For Compilatio plugin scheduled tasks, we recommend using a delay below 15 minutes between each execution" on the 2.7.1 branch ([commit](https://github.com/compilatio/moodle-plagiarism_compilatio/commit/6c0c5c99e573be563c3652c6a11781ea740cde9a)).
